### ISSUE TITLE
Regex broken!?

### ISSUE THREAD

**Issue by Daij-Djan** [julian-weinert/LinkedLog#10]
For me the regex doesn't match. Im running Xcode7.2 with the latest alcatraz build and I never see any blue, underlined, clickable text

regex seems to be "^[\d]{4}-[\d]{2}-[\d]{2}\s[\d]{2}:[\d]{2}:[\d]{2}.[\d]{3}\s[^\[]_\[\d_:\d_\]\s(.+\/([^\/:]+:\d+)):\s._"
sample line from the log (1st line) = "2016-02-15 16:22:16.330 myApp LIVE[26556:136834] /Users/dpich/Documents/MySources/myaapp-ios/myApp/Classes/AppDelegate.m:68: didFinishLaunch"

**Comment by julian-weinert** [comment]
@Daij-Djan, can you confirm this is still valid?
It's working well for me
